name: Build and Push Docker Image and deploy

on:
  push:
    branches:
      - main

jobs:
  java_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy Java Project
      working-directory: Java
      run: docker build -t manlyman/podo_repo:spring-boot -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      run: docker push manlyman/podo_repo:spring-boot

  react_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy React Project
      working-directory: React
      run: docker build -t manlyman/podo_repo:nginx -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker-compose setting
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY_PATH }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }}
        docker-compose down
        docker-compose pull
        docker-compose up -d
        docker image prune -a -f
