name: Build and Push Docker Image and deploy

on:
  push:
    branches:
      - main

jobs:
  react_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy React Project
      working-directory: React
      run: docker build -t manlyman/podo_repo:nginx -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      run: docker push manlyman/podo_repo:nginx

  java_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Run Tests with Gradle
        run: ./gradlew sixnumber:test

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results

  java_build:
    runs-on: ubuntu-latest
    needs:
      - java_test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy Java Project
      working-directory: Java
      run: docker build -t manlyman/podo_repo:spring-boot -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      run: docker push manlyman/podo_repo:spring-boot

  deploy:
    runs-on: self-hosted
    needs:
      - java_build
      - react_build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create pem after SSH login
      run: |
        echo "$KEY_PEM" > pem.key
        chmod 600 pem.key
        ssh -i pem.key -o StrictHostKeyChecking=no ubuntu@"$HOST"
      env:
        KEY_PEM: ${{ secrets.SSH_PEM_KEY }}
        HOST: ${{ secrets.EC2_HOST }}

    - name: Docker-compose update
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d
        docker image prune -a -f
