name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  java_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy Java Project
      working-directory: Java
      run: docker build -t manlyman/podo_repo:spring-boot -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      run: docker push manlyman/podo_repo:spring-boot

  react_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy React Project
      working-directory: React
      run: docker build -t manlyman/podo_repo:nginx -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    runs-on: ip-172-31-36-116

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker-compose setting
      run: |
        docker-compose -f /home/ubuntu/docker-compose.yml pull
        docker rmi -f $(docker images -f "dangling=true" -q)
        docker-compose -f /home/ubuntu/docker-compose.yml up -d
