spring:
  profiles:
    active: ${PUBLIC_URL}
    include: oauth, mail
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${PRIVATE_URL}
    port: ${REDIS_PORT}

  jwt:
    secret-key: ${SECRET_KEY}

  admin:
    set-admin-key: ${ADMIN_KEY}

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    include-message: always