spring:
  profiles:
    active: local
    include: oauth
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jwt:
    secret-key: ${SECRET_KEY}

  admin:
    set-admin-key: ${ADMIN_KEY}

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    include-message: always