spring:
  profiles:
#    active: ${PRIVATE_URL}
    include: oauth, mail
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    timezone: Asia/Seoul

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_TYPE}
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${PRIVATE_URL}
    port: ${REDIS_PORT}

  jwt:
    secret-key: ${SECRET_KEY}

  admin:
    set-admin-key: ${ADMIN_KEY}

server:
  port: 443
  ssl:
    key-store: ${SSL_PATH}
    key-store-password: pw
    key-store-type: PKCS12

  servlet:
    session:
      tracking-modes: cookie
      cookie:
        secure: true
  error:
    include-message: always